### ISSUE TITLE
Merge?

### ISSUE THREAD

**Issue by Lerentis** [go-gitea/terraform-provider-gitea#1]
Hi @techknowlogick ,

glad to see that you got the time to release the terraform provider officially. as you may or may not have noticed i continued my work on [my provider](https://github.com/Lerentis/terraform-provider-gitea) in the mean time. should we merge the two projects? the migration for the users would be rather simple as far as i see there is no drift from my last PR on gitea.com.

I would still like to continue to work on the provider in the future, so if there is interest of me getting to be a maintainer of this project, please hit me up ([mastodon](https://mastodon.social/@lerentis), or email `lerentis at uploadfilter24 dot eu`. i am no longer active on twitter).

**Comment by tobiasbp** [comment]
It would be nice to see the official Gitea provider support all the features in https://github.com/Lerentis/terraform-provider-gitea

Was this provider created as a fork of the one made by @Lerentis ?

**Comment by Lerentis** [comment]
Hi @tobiasbp ,

The history is a bit funny here. The original provider was written by @techknowlogick but not published to the terraform Registry. Another fork landed on github and in the terraform registry which I forked as there was no active development there. Some features later I opened a pr on gitea.com to merge back to origin (it got merged there and you can find it in the commit history of this repo as well), but as there was no move to release it to the terraform registry I continued with my own. And here we are today :D

So some features are included in the official provider but it seems like there is no additional development effort here as well, which is why I offered to continue to develop the provider. If it is now an official one or my provider is of no concern to me

**Comment by tobiasbp** [comment]
Thanks @Lerentis for documenting the history here. What do other people like @lunny & @pizzapim think? Is this repo dead as far as being an official Gitea project?

**Comment by techknowlogick** [comment]
Hi, Sorry about missing the pings here. Not dead at all. This repo syncs over from gitea.com because Hashicorp only accepts GitHub URLs for their provider registry. I'll add that as a note to the README, and if alright w/ @Lerentis I can create a PR for all the additional work you have done and merge into the official provider :)

**Comment by Lerentis** [comment]
Hi @techknowlogick ,

feel free to create the PR 👍 
offer still stands that i join as a maintainer here as it seems like the development effort for the terraform provider seems rather low and there is definitely a demand here. if this is not wanted i will just continue on my own again and of cause you are more than welcome to sync from time to time

**Comment by techknowlogick** [comment]
@Lerentis  Awesome. Thanks :) I've just added you to have write permissions to the repo on gitea.com.

**Comment by Lerentis** [comment]
Perfect then we hava a plan:
- merge to one official gitea terraform provider
- deprecate my fork in favor of the official one
- prepare migration guide of state files
- migrate issues here (or fix them prior)

Did I miss anything @techknowlogick ?

**Comment by tobiasbp** [comment]
Great to see this moving forwards. Thanks @techknowlogick @Lerentis

**Comment by techknowlogick** [comment]
@Lerentis yup, that's it. I've merged the other issue here into the one already on gitea.com, that checks off the last item in your list.
I've also copied your plan to a comment on the gitea.com repo: https://gitea.com/gitea/terraform-provider-gitea/issues/11

and I'll close issues on this repo in a few days so that we can track issues in one place.
